window.lessonsData = [
  {
    id: 'stilllife',
    featured: true,
    hrefHe: 'stillife-lesson.html',
    hrefEn: 'stillife-lesson.html',
    image: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT47.jpg',
    icon: '🏺',
    badgeHe: '✅ זמין',
    badgeEn: '✅ Available',
    titleHe: 'טבע דומם – Still Life',
    titleEn: 'Still Life',
    descHe: 'לגלות יקום שלם בתוך חפצי הבית הפשוטים. סזאן, מורנדי, ואן גוך ועוד – כולם מצאו שפה אמנותית דרך חפצים יומיומיים.',
    descEn: 'Discover a whole universe inside simple household objects. Cézanne, Morandi, Van Gogh and others found their artistic voice through everyday objects.',
    tagsHe: ['🍎 חפצי בית', '💡 אור וצל', '👁️ התבוננות', '🖌️ ציור'],
    tagsEn: ['🍎 Home Objects', '💡 Light & Shadow', '👁️ Observation', '🖌️ Painting'],
    kickerHe: 'חפצים, אור, צל והתבוננות',
    kickerEn: 'Objects, light, shadow & observation'
  },
  {
    id: 'cities',
    featured: false,
    hrefHe: 'cities-lesson.html',
    hrefEn: 'cities-lesson.html',
    image: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-21959-001.jpg',
    icon: '🏙️',
    badgeHe: '✅ זמין',
    badgeEn: '✅ Available',
    titleHe: 'ערים ומקומות כמקורות השראה',
    titleEn: 'Cities & Places as Inspiration',
    descHe: 'כל פינת רחוב, כל חלון מואר, כל גשר ישן – עולם שלם מחכה למכחול שלך. הופר, פיסארו, מונה ועוד.',
    descEn: 'Every street corner, every lit window, every old bridge – a whole world waits for your brush. Hopper, Pissarro, Monet and more.',
    tagsHe: ['🏛️ פרספקטיבה', '🌆 נוף עירוני', '⏱️ טיימר', '🗺️ מקומות'],
    tagsEn: ['🏛️ Perspective', '🌆 Urban Landscape', '⏱️ Timer', '🗺️ Places'],
    kickerHe: 'רחובות, חלונות, גשרים ואווירה',
    kickerEn: 'Streets, windows, bridges and atmosphere'
  },
  {
    id: 'journal',
    featured: false,
    hrefHe: 'journal-lesson.html',
    hrefEn: 'journal-lesson.html',
    image: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Frida_Kahlo_%28self_portrait%29.jpg',
    icon: '📔',
    badgeHe: '✅ זמין',
    badgeEn: '✅ Available',
    titleHe: 'יומן אישי – ציור מהנשמה',
    titleEn: 'Personal Journal – Painting from the Soul',
    descHe: 'פרידה קאלו, ואן גוך, שאגל – כולם ציירו מהרגש הפנימי. למד לתרגם רגשות, חלומות וזיכרונות לשפה ויזואלית אישית.',
    descEn: 'Frida Kahlo, Van Gogh and Chagall all painted from inner emotion. Learn to translate feelings, dreams and memories into a personal visual language.',
    tagsHe: ['🎭 רגשות', '🌙 חלומות', '⏱️ טיימר', '🎬 וידאו'],
    tagsEn: ['🎭 Emotions', '🌙 Dreams', '⏱️ Timer', '🎬 Video'],
    kickerHe: 'רגש, זיכרון ושפה אישית',
    kickerEn: 'Emotion, memory and personal language'
  },
  {
    id: 'photography',
    featured: false,
    hrefHe: 'photography-daily-life.html',
    hrefEn: 'photography-daily-life-en.html',
    image: 'https://media.tate.org.uk/aztate-prd-ew-dg-wgtail-st1-ctr-data/images/gasoline_01_1_vRqLxtU.width-420.jpg',
    icon: '📷',
    badgeHe: '✅ זמין',
    badgeEn: '✅ Available',
    titleHe: 'צילום וחיי יומיום',
    titleEn: 'Photography & Everyday Life',
    descHe: 'איך צילום, אור טבעי ורגעים פשוטים הופכים למקור השראה לרישום, ציור והתבוננות אמנותית.',
    descEn: 'How photography, natural light and simple moments become a source of inspiration for drawing, painting and artistic observation.',
    tagsHe: ['📷 צילום', '✨ השראה', '👁️ מבט', '🖼️ קומפוזיציה'],
    tagsEn: ['📷 Photography', '✨ Inspiration', '👁️ Observation', '🖼️ Composition'],
    kickerHe: 'צילום, אור טבעי וקומפוזיציה',
    kickerEn: 'Photography, natural light and composition'
  }
];
